### PR TITLE
feat: user profile and dashboard as well as the login and the logout features work

### PR DESCRIPTION
**Pull request by HamzaAhmad97**
- [x] added contact info form for teacher dashboard 
- [x] added pagination component
- [x] added header component
- [x] added user profile component 
- [x] added user details component 
- [x] added login feature
- [x] added logout feature
- [x] user profile now gets populated with the right data

### CODE REVIEW

**Review by majedalswaeer — APPROVED** [review]
Reviewed, All Clear.

**Comment by odehabuzaid** [comment]
rebuild the login functionality to redirect the user based on his ROLE <Teacher> || <Manager>

**Comment by odehabuzaid** [comment]
please do not merge until the login process complete as agreed

**Comment by HamzaAhmad97** [comment]
Please disregard this pull request but leave it open

**Pull request closed without merging**
